dw: RC1
add IBUILD_ROBOT account
start ichange hook
update clean btrfs tool
change log status echo
add more time mark
add more check task lock
add touch count

diff --git a/imake/function b/imake/function
--- a/imake/function
+++ b/imake/function
@@ -71,6 +71,7 @@ EXPORT_IBUILD_CONF()
  export JDK6_PATH=`grep '^JDK6_PATH=' $IBUILD_ROOT/conf/ibuild.conf | awk -F'JDK6_PATH=' {'print $2'}`
  export JDK7_PATH=`grep '^JDK7_PATH=' $IBUILD_ROOT/conf/ibuild.conf | awk -F'JDK7_PATH=' {'print $2'}`
  export IBUILD_GRTSRV_ID_DEFAULT=`grep '^IBUILD_GRTSRV_ID=' $IBUILD_ROOT/conf/ibuild.conf | awk -F'IBUILD_GRTSRV_ID=' {'print $2'}`
+ export IBUILD_ROBOT=`grep '^IBUILD_ROBOT=' $IBUILD_ROOT/conf/ibuild.conf | awk -F'IBUILD_ROBOT=' {'print $2'}`
  export REPO_CMD=`grep '^REPO_CMD=' $IBUILD_ROOT/conf/ibuild.conf | awk -F'REPO_CMD=' {'print $2'}`
 }
 
@@ -205,9 +206,11 @@ REPO_SYNC()
  LOG_STATUS $? repo_sync $LOG_PATH/$REPO_SYNC_LOG_NAME.log
  CCACHE_HOTFIX
 
- SPLIT_LINE "$IBUILD_ADD_STEP_1"
- time $IBUILD_ADD_STEP_1 >$LOG_PATH/$IBUILD_ADD_STEP_1_LOG_NAME.log 2>&1
- LOG_STATUS $? $IBUILD_ADD_STEP_1 $LOG_PATH/$IBUILD_ADD_STEP_1_LOG_NAME.log
+ if [[ ! -z $IBUILD_ADD_STEP_1 ]] ; then
+	SPLIT_LINE "$IBUILD_ADD_STEP_1"
+	time $IBUILD_ADD_STEP_1 >$LOG_PATH/$IBUILD_ADD_STEP_1_LOG_NAME.log 2>&1
+	LOG_STATUS $? $IBUILD_ADD_STEP_1 $LOG_PATH/$IBUILD_ADD_STEP_1_LOG_NAME.log
+ fi
 
  rm -f out
  if [[ -d /local/out ]]; then
@@ -313,29 +316,32 @@ else
  fi
 
  cp $LOG_PATH/build_info.txt $TASK_SPACE/icase-$TOWEEK/$IVER.build_info.txt
- svn add $TASK_SPACE/icase-$TOWEEK/$IVER.build_info.txt
+ svn add $TASK_SPACE/icase-$TOWEEK/$IVER.build_info.txt >/dev/null 2>&1
  svn ci -q $IBUILD_SVN_OPTION -m "auto: add $IVER_MAINFEST_NAME" $TASK_SPACE/icase-$TOWEEK/$IVER.build_info.txt
  cp $LOG_PATH/build_info.txt $AUTOUT_UPLOAD_PATH/$ICASE_UPLOAD_URL/
+}
+
+EXPORT_MANIFEST()
+{
+ export EXPORT_MANIFEST_URL=$1
+ SPLIT_LINE export_manifest
+ time $REPO_CMD manifest -r -o tmp_manifest.xml >/dev/null 2>&1
+ cp tmp_manifest.xml $EXPORT_MANIFEST_URL >/dev/null 2>&1
 }
 
 SETUP_BUILD_OUT()
 {
  [[ -d $BUILD_PATH_TOP ]] && cd $BUILD_PATH_TOP
- SPLIT_LINE export_manifest
- time $REPO_CMD manifest -r -o $LOG_PATH/manifest.xml >/dev/null 2>&1
+ EXPORT_MANIFEST $LOG_PATH/manifest.xml
+
  if [[ $RESULT != FAILED ]] ; then
 	if [[ -f images_$IBUILD_TARGET_PRODUCT.txz ]] ; then
 		cp images_$IBUILD_TARGET_PRODUCT.txz $AUTOUT_PATH/$AUTOUT_NAME/ 
 		export DOWNLOAD_PKG_NAME=images_$IBUILD_TARGET_PRODUCT.txz
-	fi
-	cd out
-	if [[ -d release-$IBUILD_TARGET_PRODUCT-$IBUILD_TARGET_BUILD_VARIANT ]] ; then
-		export REL_PKG_NAME=release-$IBUILD_TARGET_PRODUCT-$IBUILD_TARGET_BUILD_VARIANT
-	else
+	elif [[ `ls out/* | grep 'release-' | head -n1` ]] ; then
+		cd out
 		export REL_PKG_NAME=`ls | grep 'release-' | head -n1`
-	fi
-	[[ ! -z $REL_PKG_NAME ]] && tar cf $REL_PKG_NAME.tar $REL_PKG_NAME
-	if [[ -f $REL_PKG_NAME.tar ]] ; then 
+		tar cf $REL_PKG_NAME.tar $REL_PKG_NAME
 		cp $REL_PKG_NAME.tar $AUTOUT_PATH/$AUTOUT_NAME/
 		export DOWNLOAD_PKG_NAME=$REL_PKG_NAME.tar
 	else
@@ -349,19 +355,14 @@ SETUP_BUILD_OUT()
  mv $AUTOUT_PATH/$AUTOUT_NAME $AUTOUT_PATH/$IVER.$SHORT_AUTOUT_NAME
 
  if [[ ! -f $AUTOUT_UPLOAD_PATH/README ]] ; then
-	if [[ `echo $IBUILD_UPLOAD_URL | grep ssh` ]] ; then
-		export IBUILD_UPLOAD_URL_NOSSH=`echo $IBUILD_UPLOAD_URL | awk -F'ssh://' {'print $2'}` 
-		sshfs $IBUILD_UPLOAD_URL_NOSSH $AUTOUT_UPLOAD_PATH >$LOG_PATH/sshfs.log 2>&1
-	fi
- fi
-
- if [[ ! -f $AUTOUT_UPLOAD_PATH/README ]] ; then
-	export IBUILD_UPLOAD_STATUS=false
- fi
+	sshfs $IBUILD_ROBOT@$IBUILD_UPLOAD_URL $AUTOUT_UPLOAD_PATH >$LOG_PATH/sshfs.log 2>&1
+	LOG_STATUS $? sshfs_$AUTOUT_UPLOAD_PATH $LOG_PATH/sshfs.log 
+fi
 
  mkdir -p $AUTOUT_UPLOAD_PATH/$TODAY
  SPLIT_LINE upload_$TODAY_$IVER.$SHORT_AUTOUT_NAME
  cp /tmp/build-$ITASK_REV.log $AUTOUT_PATH/$IVER.$SHORT_AUTOUT_NAME/log/
+ cp /tmp/build-$ITASK_REV.log $AUTOUT_PATH/$IVER.$SHORT_AUTOUT_NAME/
  time cp -R $AUTOUT_PATH/$IVER.$SHORT_AUTOUT_NAME $AUTOUT_UPLOAD_PATH/$TODAY/
  export STATUS_CP=$?
 
@@ -383,8 +384,11 @@ BUILD_ERROR()
 	else
 		cat $CHECK_LOG >>$LOG_PATH/error.log
 	fi
+ elif [[ -f $CHECK_LOG ]] ; then
+	tail -n 50 $CHECK_LOG
+	cp $CHECK_LOG $LOG_PATH/error.log
  else
-	cat $CHECK_LOG || echo "$CHECK_LOG does not exist" >>$LOG_PATH/error.log
+	echo "$CHECK_LOG does not exist" >>$LOG_PATH/error.log
  fi
 }
 
@@ -392,7 +396,7 @@ CLEAN_EXIT()
 {
  rm -fr $TASK_SPACE/*spec.build*
  rm -f $TASK_SPACE/itask.lock
- exit
+ exit $1
 }
 
 LOG_STATUS()
@@ -400,17 +404,18 @@ LOG_STATUS()
  export CHECK_STATUS=$1
  export CHECK_SUBJECT=$2
  export CHECK_LOG=$3
+ export CHECK_LOG_NAME=`basename $CHECK_LOG`
 
  if [[ $CHECK_STATUS != 0 ]] ; then
-	SPLIT_LINE "LOG_STATUS $CHECK_SUBJECT"
+	SPLIT_LINE "ERROR LOG: $CHECK_SUBJECT"
 	BUILD_ERROR $CHECK_LOG
 	export RESULT=FAILED
         echo $CHECK_LOG >$LOG_PATH/BUILD_ERROR
 	SETUP_BUILD_OUT
 	sleep 5 && pkill -9 $IBUILD_MAKE_TOOL >/dev/null 2>&1 &
 
-	SPLIT_LINE STOP_BUILD
-	exit $CHECK_STATUS
+	SPLIT_LINE "STOP_BUILD $CHECK_LOG_NAME"
+	CLEAN_EXIT $CHECK_STATUS
  else
 	export RESULT=PASSED
  fi
